# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpX6iIcOQQJqe070Q4KETXg-lsLVceBS
"""

class SimpleChatbot:
    def __init__(self):
        self.context = {}

    def greet(self):
        return "Hello! I'm your friendly chatbot. How can I assist you today?"

    def farewell(self):
        return "Goodbye! Have a great day."

    def basic_questions(self, question):
        responses = {
            "How are you?": "I'm doing well, thank you!",
            "What's your name?": "I'm am ROBO your humble chatbot.",
            "Where are you from?": "I exist in the realm of code.",
            "What can you do?": "I can answer your questions and have a conversation with you.",
            "Who created you?": "I was created by a developer like you!"
        }
        return responses.get(question, "I'm not sure how to respond to that.")

    def remember_context(self, context):
        self.context.update(context)

    def previous_context(self):
        if self.context:
            return "Based on our previous conversation, "
        else:
            return ""

    def ask_questions(self):
        questions = ["What's your favorite color?", "How's your day going?", "Do you have any plans for the weekend?"]
        answers = []
        for question in questions:
            answer = input(question + " ")
            answers.append(answer)
        return answers

    def handle_input(self, user_input):
        response = ""
        if user_input.lower() == "bye":
            response = self.farewell()
        elif user_input in self.context:
            response = self.context[user_input]
        elif user_input.endswith("?"):
            response = self.basic_questions(user_input)
        elif user_input in question:
            response=self.ask_questions(user_input)
        else:
            response = "I'm sorry, I didn't understand that. Can you please rephrase?"
        return response


def main():
    chatbot = SimpleChatbot()
    print(chatbot.greet())

    while True:
        user_input = input("You: ")
        response = chatbot.handle_input(user_input)
        print("Bot:", response)

        if response == chatbot.farewell():
            break


if __name__ == "__main__":
    main()